name: "System Tests"

on:
  push:
    branches:
      - main

jobs:
  cli-config:
    name: "Test xffl config"
    strategy:
      matrix:
        on: [ "ubuntu-24.04"]
        python: [ "3.10", "3.11", "3.12" ]
    runs-on: ${{ matrix.on }}
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: requirements.txt

      - name: "Install Python Dependencies"
        run: python -m pip install .

      - name: "Create an xffl project using the config CLI interface."
        env:
          CHECKSUM: "45141d319f55599bfbe8f861aaea25e25b86fb0a1ec416afea13853ce0a051e0"
        run: |
          cd test/system/cli
          HASH="$(make checksum-config | tail -n 1)"
          echo "Project checksum is ${HASH}"
          test "${HASH}" == "${CHECKSUM}"

      - name: "Validate project"
        run: |
          cd test/system/cli
          make setup
          make generate-project
          xffl run --project test --validate
          make clean
